### ISSUE TITLE
TRAEFIK

### ISSUE THREAD

**Issue by Jean-Baptiste-Lasselle** [Jean-Baptiste-Lasselle/infra-kytes#12]
Virer NGINX pour le remplacer par traefik.io, et en profiter pour régler les questions de DNS

```yaml
# -- ajout live de traefik.io quickstart https://docs.traefik.io/
  reverse-proxy:
    image: traefik # The official Traefik docker image
    command: --api --docker # Enables the web UI and tells Traefik to listen to docker
    ports:
      - "80:80"     # The HTTP port
      - "8080:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
```
